/* How a level answers its move budget.

   The generator used to roll parameters from fixed constants and hope.
   Nothing knew what any particular level was *supposed* to feel like, so
   the endless run had no shape — it was noise inside a band, and the
   band was the only thing anybody had ever checked.

   To generate a level to a target you need the response curve: hold the
   goal fixed, vary the moves, and see what the clear rate does. That
   curve is different for every kind of goal — a collect level and a mud
   level do not spend moves the same way — so it is measured per kind and
   then inverted, which is how the generator turns "this level should be
   won about seven times in ten" into a move count.

     node test/calibrate.js [gamesPerPoint]

   Writes src/js/12-curve.js. Re-run it whenever the engine, the goal
   sizes, or the solver change: the numbers below are measurements, not
   opinions, and they go stale.
*/
const fs = require('fs');
const path = require('path');
const { playLevel, X } = require('./_solver.js');
const { levelDef, GK } = X;

const GAMES = +process.argv[2] || 26;
/* the move budget as a multiple of what the generator asks for today */
const SCALES = [.55, .68, .80, .92, 1.0, 1.12, 1.28, 1.50];
/* several level numbers per kind, so one unlucky map does not become the
   model for a whole goal type */
const SAMPLES = 5;

const KINDS = [GK.COLLECT, GK.MUD, GK.CRATE, GK.RESCUE, GK.SCORE, GK.BRAMBLE];

/* find generated levels of each kind to measure */
function levelsOfKind(kind, want) {
  const out = [];
  for (let n = 61; n < 700 && out.length < want; n += 1) {
    const def = levelDef(n, true);
    if (def.goals.some(g => g[0] === kind)) out.push(n);
  }
  return out;
}

function clearRate(n, def, games) {
  let won = 0;
  for (let g = 0; g < games; g++) {
    if (playLevel(n, n * 1000 + g * 7919, def).won) won++;
  }
  return won / games;
}

console.log('measuring how each goal answers its move budget');
console.log(GAMES + ' games a point, ' + SAMPLES + ' levels a kind, ' +
  SCALES.length + ' budgets — ' + (GAMES * SAMPLES * SCALES.length * KINDS.length) + ' games\n');

const table = {};
KINDS.forEach(kind => {
  const levels = levelsOfKind(kind, SAMPLES);
  if (!levels.length) { console.log(kind + ': no generated levels found'); return; }
  const row = SCALES.map(() => 0);
  levels.forEach(n => {
    const base = levelDef(n, true);   /* the fixed point, not the generator's answer */
    SCALES.forEach((s, i) => {
      const def = Object.assign({}, base, { moves: Math.max(6, Math.round(base.moves * s)) });
      row[i] += clearRate(n, def, GAMES);
    });
  });
  /* More moves can never make a level harder, so the true curve rises.
     Any dip in the measurement is sampling noise, and an inverter that
     believes a dip will read the wrong budget off it — so the row is
     made monotone by carrying the running maximum forward. That is a
     correction to noise, not a thumb on the scale. */
  const mean = row.map(v => v / levels.length);
  let run = 0;
  table[kind] = mean.map(v => { run = Math.max(run, v); return +run.toFixed(3); });
  const raw = mean.map(v => Math.round(v * 100));
  const fixed = table[kind].map(v => Math.round(v * 100));
  console.log(kind.padEnd(9) + table[kind].map((v, i) =>
    SCALES[i].toFixed(2) + 'x:' + String(Math.round(v * 100)).padStart(3) + '%').join(' '));
  console.log('         reachable by moves alone: ' +
    Math.round(table[kind][0] * 100) + '% - ' +
    Math.round(table[kind][table[kind].length - 1] * 100) + '%');
  /* printed after its own row, not before it — this line used to appear
     above the next kind's numbers and read as if it belonged to them,
     which is how a correct table gets thrown away for looking wrong */
  if (raw.join() !== fixed.join()) {
    console.log('         raw was ' + raw.join(',') + ' — carried forward where it dipped');
  }
});

/* Invert it. For a wanted clear rate, walk the measured points and read
   off the budget between them; outside the measured range, hold the end
   — extrapolating a sigmoid past its data is how you end up generating a
   level nobody can finish. */
const body = `/* Generated by test/calibrate.js — do not edit by hand.

   How each kind of goal answers its move budget, measured with the
   greedy solver over ${GAMES} games a point. MOVE_SCALES are multiples of
   the generator's own move count; CLEAR_AT[kind][i] is the share of games
   the solver won at that budget.

   The generator reads these backwards: it knows the clear rate a level is
   meant to have and asks what budget produces it. */
const MOVE_SCALES = ${JSON.stringify(SCALES)};
const CLEAR_AT = ${JSON.stringify(table, null, 2).replace(/\n/g, '\n')};

/* The lowest and highest clear rate the budget alone can produce for a
   kind. Outside that range the generator has to change the work, not the
   moves — a mud level at half its budget still clears three times in
   five, because a mud goal is a share of what the map holds. */
function budgetRange(kind) {
  const row = CLEAR_AT[kind];
  return row ? [row[0], row[row.length - 1]] : [0, 1];
}

/* the budget multiplier that lands closest to a wanted clear rate */
function budgetFor(kind, wantClear) {
  const row = CLEAR_AT[kind];
  if (!row) return 1;
  /* the curve rises with the budget, so walk it until it passes the mark */
  for (let i = 0; i < row.length; i++) {
    if (row[i] >= wantClear) {
      if (i === 0) return MOVE_SCALES[0];
      const lo = row[i - 1], hi = row[i];
      const t = hi === lo ? 0 : (wantClear - lo) / (hi - lo);
      return MOVE_SCALES[i - 1] + (MOVE_SCALES[i] - MOVE_SCALES[i - 1]) * t;
    }
  }
  return MOVE_SCALES[MOVE_SCALES.length - 1];
}
`;
fs.writeFileSync(path.join(__dirname, '..', 'src', 'js', '12-curve.js'), body);
console.log('\nwrote src/js/12-curve.js');
