/* Fit the run to its own targets, one level at a time.

   11-design.js says what share of games each level is meant to be won,
   and the generator turns that into a move budget by reading the
   response curve of the level's kind backwards. The curve is one line
   drawn through five levels of a kind; the level in front of the player
   is one map, with one blob, one arrangement and one tier's score
   demand, and it answers its budget in its own way. Validated
   (test/curve.js, levels 61-120, twelve games a level) the model landed
   twenty points off its target on the average level and fifty on the
   worst, in both directions — a relief level nobody could lose, a gate
   one player in twelve got through.

   The lane had the same problem and got the same answer: play the level,
   not the model. Each level is played at the budget the model gives it;
   if it lands wide of the target the budget moves, up or down, until the
   target is bracketed, one more point goes in the middle, and a line
   through every point measured says where the target is crossed. The
   same seeds at every budget, so a change in the clear rate is the
   budget's doing and not the deal's; and not test/curve.js's seeds, so
   the validation stays out of sample.

   A level the budget cannot steer — still cleared nine times in ten at
   six tenths of its moves, because of where its crates happened to lie —
   gets more work instead: the goal grows in steps and the budget is
   searched again at each, until the target is reachable. The other way
   round, a patch nobody could clear at twice its budget, gets less.

     node test/fit-run.js [first] [last] [gamesPerPoint] [--only=n,n,...]

   Writes src/js/13-run-fit.js for the whole range in one process, or
   with FIT_OUT=<file.json> only the rows, so the run can be fitted in
   slices side by side and folded together afterwards; a later file's
   row replaces an earlier one's for the same level, which is how a
   handful of levels are refitted without replaying three hundred:

     node test/fit-run.js --merge a.json b.json ...
*/
const fs = require('fs');
const path = require('path');
const MODULE = path.join(__dirname, '..', 'src', 'js', '13-run-fit.js');

/* ---------- writing the module ---------- */
function writeModule(rows, games) {
  rows.sort((a, b) => a.n - b.n);
  const miss = rows.reduce((s, r) => s + Math.abs(r.p - r.want), 0) / rows.length;
  const floor = rows.filter(r => r.pin === 'floor').length;
  const ceil = rows.filter(r => r.pin === 'ceiling').length;
  const worked = rows.filter(r => r.work && r.work !== 1);
  const first = rows[0].n, last = rows[rows.length - 1].n;
  const lines = [];
  for (let i = 0; i < rows.length; i += 8) {
    lines.push('  ' + rows.slice(i, i + 8).map(r => r.n + ': ' + r.moves).join(', '));
  }
  const wlines = [];
  for (let i = 0; i < worked.length; i += 8) {
    wlines.push('  ' + worked.slice(i, i + 8).map(r => r.n + ': ' + r.work).join(', '));
  }
  const body = `/* Generated by test/fit-run.js — do not edit by hand.

   The move budget of every generated level from ${first} to ${last},
   measured one level at a time: each was played at the budget the
   response curves gave it by the player who cannot see cascades
   (test/_solver.js), and the budget moved until the level landed on the
   target 11-design.js draws for it. ${games} games a point. A level with
   no row here takes the budget the curves give it.

   ${rows.length} levels fitted, mean miss ${Math.round(miss * 100)}% at that
   sample size; ${floor} pinned at the floor (easier than drawn at six tenths of
   their budget) and ${ceil} at the ceiling (harder than drawn at twice it). */
const RUN_MOVES = {
${lines.join(',\n')}
};

/* Levels whose budget could not reach the target on its own, so the
   work was changed as well: the goal is this many times what the
   generator would have asked for, before the budget above was fitted. */
const RUN_WORK = {
${wlines.join(',\n')}
};

/* the fitted budget for a level, or undefined when it was never fitted */
function fittedMoves(n) {
  return RUN_MOVES[n];
}
/* the fitted work multiplier for a level, or undefined for the usual one */
function fittedWork(n) {
  return RUN_WORK[n];
}
`;
  fs.writeFileSync(MODULE, body);
  console.log('wrote ' + MODULE + ': ' + rows.length + ' levels, mean miss ' +
    Math.round(miss * 100) + '%, pinned ' + floor + ' floor / ' + ceil + ' ceiling, ' +
    worked.length + ' with their work changed');
}

if (process.argv[2] === '--merge') {
  const byLevel = new Map();
  let games = 0;
  process.argv.slice(3).forEach(f => {
    const j = JSON.parse(fs.readFileSync(f, 'utf8'));
    j.rows.forEach(r => byLevel.set(r.n, r));
    games = j.games;
  });
  writeModule([...byLevel.values()], games);
  process.exit(0);
}

/* ---------- measuring ---------- */
const { playLevel, X, ctx } = require('./_solver.js');
const { levelDef, targetClear } = X;
/* the model's budget is the starting point, never the last fit's */
ctx.fittedMoves = () => undefined;
ctx.fittedWork = () => undefined;

const ONLY = (process.argv.find(a => a.indexOf('--only=') === 0) || '').split('=')[1];
const nums = process.argv.slice(2).filter(a => a.indexOf('--') !== 0);
const FIRST = +nums[0] || 61;
const LAST = +nums[1] || 360;
const GAMES = +nums[2] || 16;
const OUT = process.env.FIT_OUT;
const LEVELS_TO_FIT = ONLY ? ONLY.split(',').map(Number) : null;

function clearRate(n, def, moves) {
  const d = Object.assign({}, def, { moves });
  let won = 0;
  for (let g = 0; g < GAMES; g++) if (playLevel(n, n * 1000 + g * 7919, d).won) won++;
  return won / GAMES;
}

/* the level as the generator would build it with this much work, and
   the model's own budget */
function build(n, work) {
  ctx.fittedWork = () => (work === 1 ? undefined : work);
  const def = levelDef(n);
  ctx.fittedWork = () => undefined;
  return def;
}

/* where a straight line through the measured points crosses the target;
   the points nearest the crossing carry the most weight, because a
   clear rate is a sigmoid and only its middle is straight */
function crossing(pts, want) {
  const w = pts.map(([, p]) => 1 / (.05 + Math.abs(p - want)));
  const W = w.reduce((a, b) => a + b, 0);
  const mx = pts.reduce((s, [m], i) => s + w[i] * m, 0) / W;
  const my = pts.reduce((s, [, p], i) => s + w[i] * p, 0) / W;
  let sxx = 0, sxy = 0;
  pts.forEach(([m, p], i) => { sxx += w[i] * (m - mx) * (m - mx); sxy += w[i] * (m - mx) * (p - my); });
  if (sxx === 0 || sxy <= 0) return mx;
  return mx + (want - my) * sxx / sxy;
}

/* the budget search for one build of the level */
function searchMoves(n, def, want) {
  const m0 = def.moves;
  const lo = Math.max(8, Math.round(m0 * .6)), hi = Math.round(m0 * 2);
  const seen = new Map();
  const P = m => { if (!seen.has(m)) seen.set(m, clearRate(n, def, m)); return seen.get(m); };
  const p0 = P(m0);
  /* a level already within four points of its target keeps its budget:
     at this sample size a closer answer is not a truer one */
  let moves = m0, pin = '';
  if (Math.abs(p0 - want) > .04) {
    let bLo, bHi;                       /* bLo clears under the target, bHi over it */
    if (p0 >= want) {
      bHi = m0;
      for (let m = m0; ; ) {
        m = Math.max(lo, Math.floor(m * .87));
        if (P(m) < want) { bLo = m; break; }
        bHi = m;
        if (m === lo) break;
      }
    } else {
      bLo = m0;
      for (let m = m0; ; ) {
        m = Math.min(hi, Math.ceil(m * 1.15));
        if (P(m) >= want) { bHi = m; break; }
        bLo = m;
        if (m === hi) break;
      }
    }
    if (bLo === undefined) { moves = lo; pin = 'floor'; }
    else if (bHi === undefined) { moves = hi; pin = 'ceiling'; }
    else {
      if (bHi - bLo > 1) P((bLo + bHi) >> 1);
      const pts = [...seen.entries()].filter(([m]) => m >= bLo && m <= bHi);
      moves = Math.round(Math.max(bLo, Math.min(bHi, crossing(pts, want))));
      /* the answer is one of the budgets played, or between two of
         them; play it once so the row carries a measured rate */
      P(moves);
    }
  }
  return { m0, p0, moves, p: P(moves), pin, pts: [...seen.entries()].sort((a, b) => a[0] - b[0]) };
}

function fitLevel(n) {
  const want = targetClear(n);
  let work = 1;
  let def = build(n, work);
  const first = searchMoves(n, def, want);
  let best = first;
  /* The budget could not steer far enough. More work, then the budget
     again — and the other way for a level nobody could finish. */
  const ladder = best.pin === 'floor' ? [1.25, 1.5, 1.75, 2] : best.pin === 'ceiling' ? [.85, .7, .55] : [];
  for (const w of ladder) {
    def = build(n, w);
    const again = searchMoves(n, def, want);
    work = w; best = again;
    if (!again.pin) break;
  }
  return Object.assign({ n, kind: def.goals[0][0], want: +want.toFixed(3), work, m0: first.m0, p0: first.p0 }, best);
}

const todo = LEVELS_TO_FIT || (() => { const out = []; for (let n = FIRST; n <= LAST; n++) out.push(n); return out; })();
console.log('fitting ' + (LEVELS_TO_FIT ? 'levels ' + todo.join(',') : 'levels ' + FIRST + '-' + LAST) + ', ' + GAMES + ' games a point');
const rows = [];
const t0 = Date.now();
todo.forEach(n => {
  const r = fitLevel(n);
  rows.push(r);
  console.log(String(n).padStart(4) + ' ' + r.kind.padEnd(8) +
    ' want ' + Math.round(r.want * 100) + '%' +
    '  model ' + String(r.m0).padStart(3) + ' -> ' + Math.round(r.p0 * 100) + '%' +
    '  fit ' + String(r.moves).padStart(3) + (r.work !== 1 ? ' x' + r.work + ' work' : '') + ' -> ' + Math.round(r.p * 100) + '%' +
    (r.pin ? '  ' + r.pin : '') + '   (' + r.pts.length + ' points)');
  if (OUT) fs.writeFileSync(OUT, JSON.stringify({ games: GAMES, rows }));
});
console.log(Math.round((Date.now() - t0) / 1000) + 's');
if (!OUT) writeModule(rows, GAMES);
