/* ============================================================
   THE SHAPE OF THE ENDLESS RUN
   ============================================================

   The sixty handcrafted levels were authored one at a time and then
   measured. Everything after them was generated by rolling parameters
   from fixed constants, which meant no level had any intended
   difficulty at all. The run held inside its band because the constants
   were tuned in aggregate — but inside that band it was noise. Two
   hundred levels of the same thing, at random.

   A run wants a shape. Not a straight climb, which is exhausting, and
   not a flat line, which is boring: a rhythm. Relief after a hard one so
   the player is allowed to feel good, a build across the middle, and a
   gate at the end of each block that has to be earned. The gate is the
   level people remember; the relief is what makes them try it again.

   All figures here are the clear rate of the greedy solver in
   test/ai.js, which plays about as well as an attentive human who is not
   trying very hard. It is a proxy, and it is the one every difficulty
   number in this project has been measured with.

   They describe a player walking a *bare* pet, because that is the floor
   and the basis everything else was measured on. A cared-for one brings
   four more moves and twelve percent more score to the same board, and
   measured, that put the run ninety-one percent cleared — above the
   ceiling the whole project holds itself to. The numbers below are set
   so the run sits inside the band for the player who actually turns up:
   the one who feeds the animal.
   ============================================================ */

/* Ten levels to a block. The gate is the last of them; the level after a
   gate is the softest thing in the game. */
const BLOCK = 10;
const RHYTHM = [
  +.13,   /* 1  — relief. You have just come through a gate. */
  +.06,   /* 2  — still gentle, but it asks for something */
  +.02,   /* 3 */
  -.03,   /* 4  — the first one that can go wrong */
  +.05,   /* 5  — a breather in the middle of the block */
  -.04,   /* 6 */
  -.07,   /* 7 */
  -.02,   /* 8  — a small step back before the run-up */
  -.09,   /* 9  — the run-up */
  -.15    /* 10 — the gate */
];

/* The floor the run settles toward, and how fast it gets there. Ninety
   levels in it is most of the way down; it never reaches the floor, so
   there is always somewhere left to go. */
const RUN_START = 61;
const EASE_FROM = .78, EASE_TO = .61, EASE_OVER = 210;

/* Never certain, never impossible. A generated level outside these is a
   bug in the model, not a design decision. */
const CLEAR_FLOOR = .45, CLEAR_CEIL = .88;

/* The generator lands about nine points easier than it aims for.

   Measured twice over the run at different sample sizes — +7% across
   levels 61-110 at fourteen games, +11% across 61-100 at ten — so it is
   a systematic offset rather than a coin. It is the residual of the
   model: the response curves know what a move budget does on an average
   map of a kind, and the map in front of the player is not the average
   one. Corrected in one place by aiming low, which is honest about
   there being an error rather than hiding it in the constants. */
const MODEL_BIAS = .09;

/* What share of games this level is meant to be won. */
function targetClear(n) {
  if (n < RUN_START) return null;          /* the authored lane is not generated */
  const k = n - RUN_START;
  const ease = EASE_TO + (EASE_FROM - EASE_TO) * Math.exp(-k / EASE_OVER);
  const beat = RHYTHM[k % BLOCK];
  /* a little variation so the rhythm is felt rather than counted */
  const jitter = (mulberry(n * 60013)() - .5) * .04;
  return clamp(ease + beat + jitter, CLEAR_FLOOR, CLEAR_CEIL);
}

/* Whether this level is the one at the end of a block. The map screen
   marks it, and the level card says so: a wall you did not know was
   coming is just an unfair level. */
function isGate(n) {
  return n >= RUN_START && ((n - RUN_START) % BLOCK) === BLOCK - 1;
}
