/* Generated by test/calibrate.js — do not edit by hand.

   How each kind of goal answers its move budget, measured with the
   greedy solver over 20 games a point. MOVE_SCALES are multiples of
   the generator's own move count; CLEAR_AT[kind][i] is the share of games
   the solver won at that budget.

   The generator reads these backwards: it knows the clear rate a level is
   meant to have and asks what budget produces it. */
const MOVE_SCALES = [0.55,0.68,0.8,0.92,1,1.12,1.28,1.5];
const CLEAR_AT = {
  "collect": [
    0.05,
    0.2,
    0.42,
    0.72,
    0.76,
    0.9,
    0.96,
    1
  ],
  "mud": [
    0.32,
    0.52,
    0.63,
    0.74,
    0.75,
    0.87,
    0.89,
    0.99
  ],
  "crate": [
    0.38,
    0.45,
    0.7,
    0.79,
    0.81,
    0.84,
    0.92,
    0.95
  ],
  "rescue": [
    0.33,
    0.36,
    0.57,
    0.57,
    0.64,
    0.64,
    0.7,
    0.78
  ],
  "score": [
    0.03,
    0.06,
    0.2,
    0.47,
    0.65,
    0.81,
    0.94,
    0.99
  ],
  "bramble": [
    0.25,
    0.34,
    0.44,
    0.49,
    0.49,
    0.56,
    0.67,
    0.72
  ]
};

/* The lowest and highest clear rate the budget alone can produce for a
   kind. Outside that range the generator has to change the work, not the
   moves — a mud level at half its budget still clears three times in
   five, because a mud goal is a share of what the map holds. */
function budgetRange(kind) {
  const row = CLEAR_AT[kind];
  return row ? [row[0], row[row.length - 1]] : [0, 1];
}

/* the budget multiplier that lands closest to a wanted clear rate */
function budgetFor(kind, wantClear) {
  const row = CLEAR_AT[kind];
  if (!row) return 1;
  /* the curve rises with the budget, so walk it until it passes the mark */
  for (let i = 0; i < row.length; i++) {
    if (row[i] >= wantClear) {
      if (i === 0) return MOVE_SCALES[0];
      const lo = row[i - 1], hi = row[i];
      const t = hi === lo ? 0 : (wantClear - lo) / (hi - lo);
      return MOVE_SCALES[i - 1] + (MOVE_SCALES[i] - MOVE_SCALES[i - 1]) * t;
    }
  }
  return MOVE_SCALES[MOVE_SCALES.length - 1];
}
