/* Generated by test/calibrate.js — do not edit by hand.

   How each kind of goal answers its move budget, measured with the
   player who cannot see cascades (test/_solver.js) over 16-20 games a point. MOVE_SCALES are multiples of
   the generator's own move count; CLEAR_AT[kind][i] is the share of games
   the solver won at that budget.

   The generator reads these backwards: it knows the clear rate a level is
   meant to have and asks what budget produces it. */
const MOVE_SCALES = [0.55,0.68,0.8,0.92,1,1.12,1.28,1.5];
const CLEAR_AT = {
  "collect": [
    0,
    0.04,
    0.19,
    0.42,
    0.53,
    0.74,
    0.88,
    0.96
  ],
  "mud": [
    0.925,
    0.988,
    1,
    1,
    1,
    1,
    1,
    1
  ],
  "crate": [
    0.51,
    0.64,
    0.71,
    0.82,
    0.87,
    0.92,
    0.94,
    0.98
  ],
  "rescue": [
    0.48,
    0.48,
    0.53,
    0.67,
    0.67,
    0.79,
    0.9,
    0.9
  ],
  "score": [
    0.075,
    0.175,
    0.237,
    0.388,
    0.537,
    0.775,
    0.963,
    1
  ],
  "bramble": [
    0.425,
    0.475,
    0.575,
    0.637,
    0.675,
    0.7,
    0.75,
    0.775
  ],
  "mole": [
    0.925,
    0.938,
    0.975,
    0.975,
    0.975,
    0.988,
    0.988,
    0.988
  ]
};

/* The lowest and highest clear rate the budget alone can produce for a
   kind. Outside that range the generator has to change the work, not the
   moves — a mud level at half its budget still clears three times in
   five, because a mud goal is a share of what the map holds. */
function budgetRange(kind) {
  const row = CLEAR_AT[kind];
  return row ? [row[0], row[row.length - 1]] : [0, 1];
}

/* the budget multiplier that lands closest to a wanted clear rate */
function budgetFor(kind, wantClear) {
  const row = CLEAR_AT[kind];
  if (!row) return 1;
  /* the curve rises with the budget, so walk it until it passes the mark */
  for (let i = 0; i < row.length; i++) {
    if (row[i] >= wantClear) {
      if (i === 0) return MOVE_SCALES[0];
      const lo = row[i - 1], hi = row[i];
      const t = hi === lo ? 0 : (wantClear - lo) / (hi - lo);
      return MOVE_SCALES[i - 1] + (MOVE_SCALES[i] - MOVE_SCALES[i - 1]) * t;
    }
  }
  return MOVE_SCALES[MOVE_SCALES.length - 1];
}
