/* Generated by test/calibrate.js — do not edit by hand.

   How each kind of goal answers its move budget, measured with the
   greedy solver over 26 games a point. MOVE_SCALES are multiples of
   the generator's own move count; CLEAR_AT[kind][i] is the share of games
   the solver won at that budget.

   The generator reads these backwards: it knows the clear rate a level is
   meant to have and asks what budget produces it. */
const MOVE_SCALES = [0.55,0.68,0.8,0.92,1,1.12,1.28,1.5];
const CLEAR_AT = {
  "collect": [
    0.085,
    0.208,
    0.508,
    0.685,
    0.731,
    0.908,
    0.962,
    0.985
  ],
  "mud": [
    0.985,
    0.992,
    0.992,
    0.992,
    1,
    1,
    1,
    1
  ],
  "crate": [
    0.469,
    0.715,
    0.731,
    0.854,
    0.862,
    0.869,
    0.938,
    0.962
  ],
  "rescue": [
    0.346,
    0.5,
    0.608,
    0.631,
    0.631,
    0.723,
    0.746,
    0.885
  ],
  "score": [
    0.023,
    0.1,
    0.238,
    0.538,
    0.554,
    0.815,
    0.908,
    0.969
  ],
  "bramble": [
    0.415,
    0.415,
    0.508,
    0.615,
    0.623,
    0.623,
    0.723,
    0.777
  ],
  "mole": [
    0.754,
    0.808,
    0.815,
    0.823,
    0.931,
    0.931,
    0.931,
    0.954
  ]
};

/* The lowest and highest clear rate the budget alone can produce for a
   kind. Outside that range the generator has to change the work, not the
   moves — a mud level at half its budget still clears three times in
   five, because a mud goal is a share of what the map holds. */
function budgetRange(kind) {
  const row = CLEAR_AT[kind];
  return row ? [row[0], row[row.length - 1]] : [0, 1];
}

/* the budget multiplier that lands closest to a wanted clear rate */
function budgetFor(kind, wantClear) {
  const row = CLEAR_AT[kind];
  if (!row) return 1;
  /* the curve rises with the budget, so walk it until it passes the mark */
  for (let i = 0; i < row.length; i++) {
    if (row[i] >= wantClear) {
      if (i === 0) return MOVE_SCALES[0];
      const lo = row[i - 1], hi = row[i];
      const t = hi === lo ? 0 : (wantClear - lo) / (hi - lo);
      return MOVE_SCALES[i - 1] + (MOVE_SCALES[i] - MOVE_SCALES[i - 1]) * t;
    }
  }
  return MOVE_SCALES[MOVE_SCALES.length - 1];
}
