/* Pictures into the page.

   The game draws everything, and a few things it now shows instead: the
   backdrops and room pieces generated as a trial against the drawn ones
   (art/, see README "The first pictures"). They go in the way the logo
   does — as data URIs inside the one HTML file — so the shipped game
   still fetches nothing and still works in flight mode.

   Every file in art/ is re-encoded as WebP through the browser's own
   encoder, at no more than MAX pixels across, and written to
   src/js/03-art.js. A file named furniture-*.png is keyed out: the white
   it was generated on becomes transparent, feathered over a few levels
   so the outline keeps its edge.

     node tools/art-embed.js      ->  src/js/03-art.js
*/
const path = require('path');
const fs = require('fs');
const { launch } = require('./_pw.js');

const DIR = path.join(__dirname, '..', 'art');
const OUT = path.join(__dirname, '..', 'src', 'js', '03-art.js');
const MAX = 1400;
const QUALITY = .84;

(async () => {
  const files = fs.existsSync(DIR)
    ? fs.readdirSync(DIR).filter(f => /\.(png|jpe?g|webp)$/i.test(f)).sort()
    : [];
  const browser = await launch();
  const page = await browser.newPage();
  const out = {};
  for (const f of files) {
    const buf = fs.readFileSync(path.join(DIR, f));
    const mime = /\.png$/i.test(f) ? 'image/png' : /\.webp$/i.test(f) ? 'image/webp' : 'image/jpeg';
    const src = 'data:' + mime + ';base64,' + buf.toString('base64');
    const key = f.replace(/\.[a-z]+$/i, '');
    const keyOut = /^furniture-/.test(key) || /^cut-/.test(key);
    const res = await page.evaluate(async ({ src, MAX, QUALITY, keyOut }) => {
      const im = new Image();
      im.src = src;
      await im.decode();
      const k = Math.min(1, MAX / im.naturalWidth);
      const w = Math.round(im.naturalWidth * k), h = Math.round(im.naturalHeight * k);
      const c = document.createElement('canvas');
      c.width = w; c.height = h;
      const x = c.getContext('2d');
      x.drawImage(im, 0, 0, w, h);
      if (keyOut) {
        /* near-white to transparent, with a short ramp so antialiased
           outline pixels fade rather than keep a white fringe */
        const d = x.getImageData(0, 0, w, h);
        const p = d.data;
        for (let i = 0; i < p.length; i += 4) {
          const m = Math.min(p[i], p[i + 1], p[i + 2]);
          if (m >= 246) p[i + 3] = 0;
          else if (m >= 226) p[i + 3] = Math.round(255 * (246 - m) / 20);
        }
        x.putImageData(d, 0, 0);
      }
      return { w, h, uri: c.toDataURL('image/webp', QUALITY) };
    }, { src, MAX, QUALITY, keyOut });
    out[key] = res;
    console.log('  ' + f + ' -> ' + res.w + 'x' + res.h + ', ' + Math.round(res.uri.length * .75 / 1024) + ' KB');
  }
  await browser.close();

  const lines = Object.keys(out).map(k =>
    '  ' + JSON.stringify(k) + ': { w: ' + out[k].w + ', h: ' + out[k].h + ', src: "' + out[k].uri + '" }');
  const body = `/* GENERATED by tools/art-embed.js from art/. Do not edit — run the tool
   again. Pictures the game shows rather than draws; see that tool. */
const ART_SRC = {
${lines.join(',\n')}
};

/* An image for a key once it has decoded, or null until then. The first
   ask starts the decode and repaints the screens when it lands, so a
   caller draws its drawn fallback this frame and the picture the next. */
const ART_IMG = {};
function artImage(key) {
  const e = ART_SRC[key];
  if (!e) return null;
  let im = ART_IMG[key];
  if (!im) {
    im = ART_IMG[key] = new Image();
    im.decoding = 'async';
    im.onload = () => { im._ready = true; if (typeof EV !== 'undefined') EV.emit('repaint'); };
    im.src = e.src;
  }
  return im._ready ? im : null;
}
/* start every decode as soon as the page is up, so a shop thumbnail or a
   room opened in the first second already has its picture */
setTimeout(() => Object.keys(ART_SRC).forEach(artImage), 0);
`;
  fs.writeFileSync(OUT, body);
  console.log('wrote ' + OUT + ' (' + Math.round(body.length / 1024) + ' KB)');
})().catch(e => { console.error(e.message); process.exit(1); });
